version: "3.6"
networks:
  backend:
    external: true
    name: "backend"
services:
  carl:
    container_name: "carl"
    env_file: .env
    hostname: "carl"
    image: "mglennon/carl:latest"
    restart: "unless-stopped"
    networks:
      - backend
    labels:
      - "com.centurylinklabs.watchtower.enable=false"